#ifndef IGNUM01_UNIXCLIENT_H
#define IGNUM01_UNIXCLIENT_H

#include "IGNUM01_UNIXCLIENT_global.h"

class IGNUM01_UNIXCLIENT_EXPORT IGNUM01_UNIXCLIENT
{
public:
    IGNUM01_UNIXCLIENT();
};

#endif // IGNUM01_UNIXCLIENT_H
