#ifndef IGNUM01_UNIXCLIENT_GLOBAL_H
#define IGNUM01_UNIXCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IGNUM01_UNIXCLIENT_LIBRARY)
#  define IGNUM01_UNIXCLIENT_EXPORT Q_DECL_EXPORT
#else
#  define IGNUM01_UNIXCLIENT_EXPORT Q_DECL_IMPORT
#endif

#endif // IGNUM01_UNIXCLIENT_GLOBAL_H
